-- 2교대 관련 컬럼 추가
ALTER TABLE jd ADD COLUMN IF NOT EXISTS is_two_shift BOOLEAN DEFAULT FALSE;
ALTER TABLE jd ADD COLUMN IF NOT EXISTS work_start_time2 VARCHAR(10);
ALTER TABLE jd ADD COLUMN IF NOT EXISTS work_end_time2 VARCHAR(10);

